config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :rooms do
    resources :reservations
    collection do
      get 'search'
    end
  end
  devise_for :users
  root 'top#index'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations
  belongs_to :user
  mount_uploader :room_image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reservations
  has_many :rooms

  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable, :trackable
  
  mount_uploader :profile_image_id, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  private
      def sign_in_required
          redirect_to new_user_session_url unless user_signed_in?
      end
      def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :profile, :profile_image_id)
      end

  protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
      end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @user = current_user
    @reservations = @user.reservations
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @room = @reservation.room


    @charge = params[:charge]
    @started = params[:started_at]
    @finished = params[:finished_at]
    @peoples = params[:peoples]
    @user = params[:user_id]
    @room_id = params[:room_id]
    @stay = (@finished.to_date - @started.to_date).to_i
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to user_path(current_user), notice: "予約が完了しました" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.permit(:user_id, :started_at, :finished_at, :peoples, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:index, :search]
  
  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = Room.find(params[:id])
    @user = @room.user
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice:"部屋を登録しました" }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    @room = Room.find(params[:id])
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to user_path(current_user), notice: "情報を更新しました" }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: "部屋を削除しました" }
      format.json { head :no_content }
    end
  end
  def search
    @results = @q.result
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = current_user.id
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :introduction, :charge, :address, :room_image, :user_id)
    end

    def set_q
      @q = Room.ransack(params[:q])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  before_action :sign_in_required, only: [:show]
  before_action :set_q, only: [:index, :search]

  def index
  end

  def search
    @results = @q.result
  end



  private
    def set_q
      @q = Room.ransack(params[:q])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to current_user, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelSerch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="site-header contents-width">
    <div class="wrapper site-header__wrapper">
      <div class="site-header__start">
        <%= link_to "HotelSerch", root_path, class: "brand" %>
      </div>
      <div class="site-header__middle">
        <nav class="nav">
          <ul class="nav__wrapper">
            <% if user_signed_in? %>
              <li class="nav__item"><%= link_to "お部屋一覧", rooms_path %></li>
              <li class="nav__item"><%= link_to "ユーザー一覧", users_path %></li>
              <li class="nav__item"><%= link_to 'マイページ', user_path(current_user.id) %></li>
              <li class="nav__item"><%= link_to 'アカウント変更', edit_user_registration_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "button is-success nav-item" %></li>
            <% else %>
              <li><%= link_to 'サインアップ', new_user_registration_path, class: "button is-info nav-item" %></li>
              <li><%= link_to 'ログイン', new_user_session_path, class: "button is-success nav-item" %></li>
            <% end %>
          </ul>
        </nav>
        <div class="nav__toggle head-icon">
        <% if user_signed_in? %>
          <% if current_user.profile_image_id? %>
            <%= image_tag current_user.profile_image_id.url %>
          <% else %>
            <%= image_tag "profile_icon.png" %>
          <% end %>
        <% else %>
          <%= image_tag "/16_2_282.png" %>
        <% end %>
        </div>
      </div>
    </div>
  </header>
    

    <%= yield %>
  </body>
  <footer>
  kay.original©
  </footer>
  <%= javascript_pack_tag 'header.js'%>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :入室日 %>
    <%= form.date_select :started_at %>日
  </div>

  <div class="field">
    <%= form.label :退室日 %>
    <%= form.date_select :finished_at %>日
  </div>

  <div class="field">
    <%= form.label :人数 %>
    <%= form.number_field :peoples %>
  </div>

  <div class="actions">
    <%= form.submit '予約する'%>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>
<header class="everypage-head contents-width">
  <h1>予約一覧</h1>
</header>
<div class="contents-width reserve-index">
<table class="reserve-table">
  <thead>
    <tr>
      <th>部屋イメージ</th>
      <th>部屋の名前</th>
      <th>宿泊開始日</th>
      <th>退室日</th>
      <th>人数</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td class="reserve-image"><%= image_tag reservation.room.room_image.url %></td>
        <td class="under-line">
          <%= link_to reservation.room.name, room_path(reservation.room.id) %>
        </td>
        <td><%= reservation.started_at %></td>
        <td><%= reservation.finished_at %></td>
        <td><%= reservation.peoples %>人</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/reservations/new.html.erb
<header class="everypage-head contents-width">
<h2>予約確認</h2>
</header>
<div class="contents-width confirm-form">
<%= form_with url: reservations_path do |form| %>
  <div class="charge field">
    <h3>一泊一人あたり料金</h3>
    <%= @charge %>円
  </div>
  <div class="field">
    <%= form.label :入室日 %>
    <%= form.text_field :started_at, :value => @started, readonly: true %>
  </div>

  <div class="field">
    <%= form.label :退室日 %>
    <%= form.text_field :finished_at, :value => @finished, readonly: true %>
  </div>

  <div class="field">
    <h3>滞在日数</h3>
    <%= @stay %>
  </div>

  <div class="field">
    <%= form.label :人数 %>
    <%= form.number_field :peoples, :value => @peoples, readonly: true %>
  </div>

  <div class="field">
    <h3>合計料金</h3>
    <%= @stay.to_i*@peoples.to_i*@charge.to_i %>
  </div>
        
  <%= form.hidden_field :user_id, :value => params[:user_id] %>
  <%= form.hidden_field :room_id, :value => params[:room_id] %>

  <div class="actions">
    <%= form.submit '予約を完了する'%>
  </div>
<% end %>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @reservation.started_at %>
</p>

<p>
  <strong>Finished at:</strong>
  <%= @reservation.finished_at %>
</p>

<p>
  <strong>Peoples:</strong>
  <%= @reservation.peoples %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :部屋名 %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :詳細 %>
    <%= form.text_field :introduction %>
  </div>

  <div class="field">
    <%= form.label :料金 %>
    <%= form.text_field :charge %>
  </div>

  <div class="field">
    <%= form.label :エリア %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :部屋のイメージ %>
    <%= form.file_field :room_image, accept: 'image/jpeg,image/gif,image/png' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="contents-width">
  <br>
  <br>
  <h1>部屋情報を変更</h1>

  <%= render 'form', room: @room %>
  <br>
  <%= link_to '詳細', @room %> |
  <%= link_to 'お部屋一覧へ', rooms_path %>
  <br>
  <br>
  <br>
</div>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>
<header class="everypage-head contents-width">
<h1>お部屋一覧</h1>
<%= link_to 'お部屋を貸す', new_room_path, class:"lend"%>
</header>
<div class="contents-width user-card">
  <% @rooms.each do |room| %>
    <div class="card">
    <%= link_to room_path(room.id) do %>
      <div class="card-image">
      <figure class="img">
      <% if room.room_image? %>
        <%= image_tag room.room_image.to_s %>
      <% else %>
        <%= image_tag "noimage.svg", :size => '100x100' %>
      <% end %>
      </figure>
    </div>
    <% end %>
    <div class="card-bottom">
      <div class="card-content">
        <div class="room-content">
          <%= link_to room.name, room_path(room.id) %><br>
          <%= link_to room.charge, room_path(room.id) %><br>
          <%= link_to room.address, room_path(room.id) %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<br>

app/views/rooms/new.html.erb
<div class= "contents-width">
  <h1>お部屋を貸す</h1>

  <%= render 'form', room: @room %>

  <%= link_to 'お部屋一覧へ', rooms_path %>
</div>

app/views/rooms/search.html.erb
<header class="everypage-head contents-width">
  <h1>検索結果</h1>
</header>
<div class="contents-width user-card">
  <% @results.each do |room| %>
    <div class="card">
    <%= link_to room_path(room.id) do %>
      <div class="card-image">
      <figure class="img">
      <% if room.room_image? %>
        <%= image_tag room.room_image.to_s %>
      <% else %>
        <%= image_tag "noimage.svg", :size => '100x100' %>
      <% end %>
      </figure>
    </div>
    <% end %>
    <div class="card-bottom">
      <div class="card-content">
        <div class="room-content">
          <%= link_to room.name, room_path(room.id) %><br>
          <%= link_to room.charge, room_path(room.id) %><br>
          <%= link_to room.address, room_path(room.id) %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

<br>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>
<div class="contents-width detail-contents">
  <div class="room-detail">
    <p>
      <% if @room.room_image? %>
      <%= image_tag @room.room_image.to_s %>
      <% else %>
      <%= image_tag "noimage.svg" %>
      <% end %>
    </p>

    <p>
      <strong>部屋名：</strong>
      <%= @room.name %>
    </p>

    <p>
      <strong>エリア：</strong>
      <%= @room.address %>
    </p>
    <p>
      <strong>詳細：</strong> <br>
      <%= @room.introduction %>
    </p>

    <p>
      <strong>一泊一人あたり料金：</strong>
      <%= @room.charge %>円
    </p>
    <br>
    <div class="option">
      <% if @user == current_user %>
      <%= link_to '編集', edit_room_path(@room), class:"button is-dark" %> |
      <%= button_to '削除', room_path(@room), method: :delete, data: { confirm: 'Are you sure?' }, class:"button is-dark" %> |
      <%= link_to '戻る', rooms_path, class:"button is-dark" %>
      <% else %>
      <%= link_to '戻る', rooms_path, class:"button is-dark" %>
      <% end %>
    </div>
  </div>
  <div class="reservation-form">
    <%= form_with url: new_reservation_path, method: :get do |form| %>
      <h3>一泊一人あたり料金：<%= @room.charge %>円</h3>
      <%= form.hidden_field :charge, :value => @room.charge %>
      <div class="field">
        <%= form.label :入室日 %>
        <%= form.date_field :started_at %>
      </div>
    
      <div class="field">
        <%= form.label :退室日 %>
        <%= form.date_field :finished_at %>
      </div>
    
      <div class="field">
        <%= form.label :人数 %>
        <%= form.number_field :peoples %>
      </div>
            
      <%= form.hidden_field :user_id, :value => current_user.id %>
      <%= form.hidden_field :room_id, :value => @room.id %>

      <div class="actions">
        <%= form.submit '予約する'%>
      </div>
    <% end %>
  </div>
</div>

app/views/top/index.html.erb
<div class="main1">
  <h1 class="main1-header">魅力ある宿泊施設を予約</h1>  
  <section class="search-block contents-width">
    <div class="search">
    <%= search_form_for @q, url: search_rooms_path do |f| %>
      <%= f.label :address, 'エリア検索' %>
      <%= f.search_field :address_cont %>
      <%= f.submit '検索', class:"button is-dark is-small" %>
    <% end %>
    </div>
    <div class="search">
    <%= search_form_for @q, url: search_rooms_path do |f| %>
      <%= f.label :introduction_or_name_or_charge_or_address, 'キーワード検索' %>
      <%= f.search_field :introduction_or_name_or_charge_or_address_cont %>
      <%= f.submit '検索', class:"button is-dark is-small" %>
    <% end %>
  </div>
  </section>
</div>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<div class="form contents-width">

  <%= form_for @user do |f| %>

    <div class="field">
      <%= f.label :ユーザー名 %>
      <%= f.text_field :username, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :メールアドレス %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      <%= f.label :自己紹介 %>
      <%= f.text_field :profile %>
    </div>

    <div class="field">
      <%= f.label :プロフィール画像 %>
      <button type="button" class="btn btn-outline-secondary rounded-pill">
       <%= f.file_field :profile_image_id, accept: 'image/jpeg,image/gif,image/png' %>
      </button>
    </div>

    <div class="actions">
      <%= f.submit "編集する" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1 class="contents-width everypage-head">ユーザー一覧</h1>
<div class="contents-width user-card">
  <% @users.each do |user| %>
    <div class="card">
      <%= link_to user_path(user) do %>
        <div class="card-image">
          <figure class="img">
          <% if user.profile_image_id? %>
            <%= image_tag user.profile_image_id.url %>
          <% else %>
            <%= image_tag "noimage.svg" %>
          <% end %>
          </figure>
        </div>
      <% end %>
        <div class="card-bottom">
          <div class="card-content">
            <div class="content">
              <%= link_to user.username, user_path(user.id) %>
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<header class="everypage-head contents-width ">
  <% if @user.id == current_user.id %>
    <h1>マイページ</h1>
  <% else %>
    <h1><%= @user.username %>さんのページ</h1>
  <% end %>
</header>
<section class="contents-width">
  <div class="mypage-top">
    <div class="mypage-icon">
      <figure class="mypage-image">
        <% if @user.profile_image_id? %>
        <%= image_tag @user.profile_image_id.url %>
        <% else %>
        <%= image_tag "profile_icon.png" %>
        <% end %>
      </figure>
      <div class="mypage-info">
        <%= @user.username %><br>
        <% if @user.id == current_user.id %>
        <%= @user.email %><br>
        <% end %>
      </div>
    </div>
    <div class="mypage-date">
      <% if @user.id == current_user.id %>
        <%= link_to "お部屋を貸す", new_room_path %>
        <%= link_to "予約一覧", reservations_path %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mypage-profile">
    <div class="profile-contents">
    <% if @user.profile? %>
      <%= @user.profile %>
    <% else %>
      <p>プロフィールが設定されていません</p>
    <% end %>
    </div>
    <div class="edit-btn">
      <% if @user.id == current_user.id %>
      <%= link_to "プロフィールを編集", edit_user_path, class:"btn" %>
      <% end %>
    </div>
  </div>
</section>
<div class="contents-width lend-content">
<h2>〜貸す部屋〜</h2>
<div class="lend-card">
  <% @rooms.each do |room| %>
    <div class="card">
        <%= link_to room_path(room.id) do %>
          <div class="card-image">
            <figure class="img">
              <% if room.room_image? %>
                <%= image_tag room.room_image.to_s %>
              <% else %>
                <%= image_tag "noimage.svg" %>
              <% end %>
            </figure>
          </div>
        <% end %>
        <div class="card-bottom">
          <div class="card-content">
            <div class="mypage-content">
              <%= link_to room.name, room_path(room.id) %><br>
              <%= link_to room.address, room_path(room.id) %><br>
              <%= link_to room.charge, room_path(room.id) %>
            </div>
          </div>
        </div>
    </div>
  <% end %>
  </div>
</div>